version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
            - mongo
        volumes:
            - .:/var/www/html/
            - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./xdebug_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql:5.7
        restart: always
        ports:
            - "9906:3306"
        volumes:
            - mysql:/var/lib/mysql
        env_file:
            - '.env'
         
    mongo:
      image: mongo:5.0
      container_name: mongo
      restart: unless-stopped
      ports:
        - "27017:27017"
      volumes:
        - mongo-db:/data/db
      env_file:
        - '.env'
volumes:
    mysql:
    mongo-db: