version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
            - mongo
        volumes:
            - .:/var/www/html/
            - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./xdebug_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"
         
    mongo:
      image: mongo:5.0
      container_name: mongo
      environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=password
      restart: unless-stopped
      ports:
        - "27017:27017"
      volumes:
        - ./db:/data/db
     